# Generated by Django 3.2.5 on 2021-08-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bincardcreation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Material_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display', to='bincardcreation.materialsinventory'),
        ),
    ]
