# Generated by Django 3.2.5 on 2021-09-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bincardcreation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='Verification_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
