# Generated by Django 3.2.5 on 2021-08-10 04:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bincardcreation', '0007_remove_material_receipt_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialsInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Material_Code', models.CharField(max_length=255, unique=True)),
                ('Material_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Material_Location', models.CharField(blank=True, max_length=255, null=True)),
                ('Unit_of_Measurement', models.CharField(blank=True, max_length=255, null=True)),
                ('Maximum_Level', models.IntegerField(blank=True, null=True)),
                ('Minimum_Level', models.IntegerField(blank=True, null=True)),
                ('Re_order_Level', models.IntegerField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='material',
            old_name='balance',
            new_name='Balance',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='doc_no',
            new_name='Doc_no',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='issue',
            new_name='Issue',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='received_from',
            new_name='Received_From',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='transaction_type',
            new_name='Transaction_Type',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='verification_date',
            new_name='Verification_Date',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='verified_by',
            new_name='Verified_By',
        ),
        migrations.RemoveField(
            model_name='material',
            name='material_name',
        ),
        migrations.AddField(
            model_name='material',
            name='Number_Of_Received',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='Number_Of_issued',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='Material_Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bincardcreation.materialsinventory'),
            preserve_default=False,
        ),
    ]
