# Generated by Django 3.2.5 on 2021-08-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bincardcreation', '0009_rename_doc_no_material_document_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='Issue',
            new_name='Issue_From',
        ),
    ]
